# netlify.toml

[build]
  command = ""    # üres, nincs build lépés
  publish = "."   # a gyökérkönyvtárat szolgálja ki (index.html stb.)

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    skip = true   # ez teljesen lekapcsolja a Next.js plugint
